### ISSUE TITLE
requesting foxy release

### ISSUE THREAD

**Issue by tfoote** [ros-visualization/rqt_console#38]
The last release in foxy is 1.1.1 

PRs #21 and #28 were landed into the foxy branch after that but there has not been a release which includes the solutions which are in [`foxy-devel`](https://github.com/ros-visualization/rqt_console/commits/foxy-devel). 

Note that in the index foxy is indexed to [`dashing-devel`](https://github.com/ros-visualization/rqt_console/commits/dashing-devel)

**Comment by arne48** [comment]
I am currently trying to figure out the best approach to get an updated release 2.0.2 for foxy.
Because the foxy-devel branch was reverted to version 1.1.1 after it was branched off of 2.0.0
Currently, I think one way could be to reset the foxy-devel branch to 2.0.0 and then rebase or fast-forward to the humble branch, aka 2.0.2
But my gut feeling for using reset is pretty bad.
Another more practical way could be changing the devel_branch in the gbp repository for foxy to humble and get the 2.0.2 version that way.
Afterward, we could just wait out the time until next year when foxy enters its EOL.
I already tested the current humble branch in foxy, and it works, so for this release, this could be a non-intrusive solution.

Which one would you @tfoote prefer?

But maybe I also oversee the obvious in that case; I would also be very thankful for a hint :)

**Comment by tfoote** [comment]
We don't need to push that far forward. It would be fine to just cut a 1.1.2 release with the patches staged on the foxy-devel branch already. The specific fix has been backported directly. The fixes are in f174bd94e99001c945e469e199a94a2383ebd2aa and 9442cc8b5fb7166bc700ebb50ad4c48a300e174c 

Since the 2.0.0 number change was only in the source and not released into foxy, it being reverted isn't a problem. 

It does look like the changes in the humble branch would be fine to release into foxy. But I'd suggest for now doing the simplest solution of just going to 1.1.2 on the foxy branch. It looks like the source branch should be updated to `foxy-devel` in the rosdistro and release repository from the previously unforked `dashing-devel` but otherwise it's just a patch release.

**Comment by arne48** [comment]
Cherry-picking is actually another good idea I just wasn't sure about 1.x version tree.
Thank you very much for clarifying this; I now cherry-picked [#21](https://github.com/ros-visualization/rqt_console/pull/21) and [#28](https://github.com/ros-visualization/rqt_console/pull/28).
During testing, I noticed the bug that was fixed with [#37](https://github.com/ros-visualization/rqt_console/pull/37) and cherry-picked that commit as well.
Compared to version 2.0.2, this version now seems to be only short of [#31](https://github.com/ros-visualization/rqt_console/pull/31), but this should be fine as here [ros2/ros2cli#627](https://github.com/ros2/ros2cli/pull/627), it is discussed that this would break on focal.
I also bloomed the new version already.
Thank you very much for your help [@tfoote](https://github.com/tfoote) :)

I hope closing this issue would be therefore fine now.
